export interface UserStory {
  id: string;
  title: string;
  capability: string;
}

export const USER_STORIES: UserStory[] = [
  { id: "US-01", title: "Create project from idea/outline/template/import", capability: "project.create.multi-mode" },
  { id: "US-02", title: "Configure language globally and per project", capability: "settings.locale.scoped" },
  { id: "US-03", title: "Define project metadata", capability: "project.metadata.edit" },
  { id: "US-04", title: "Duplicate/archive/delete projects", capability: "project.lifecycle.manage" },
  { id: "US-05", title: "Restore from local backup pack", capability: "backup.restore.zip" },
  { id: "US-06", title: "Build story bible", capability: "bible.manage" },
  { id: "US-07", title: "Manage character sheets", capability: "character.manage" },
  { id: "US-08", title: "Manage locations/lore/timeline/glossary", capability: "world.timeline.manage" },
  { id: "US-09", title: "Structure chapters/scenes with reordering", capability: "chapter.scene.reorder" },
  { id: "US-10", title: "Set chapter objectives/hooks/status", capability: "chapter.objectives.hooks" },
  { id: "US-11", title: "View continuity conflicts", capability: "continuity.detect" },
  { id: "US-12", title: "Run AI planning audit with preview", capability: "ai.audit.preview" },
  { id: "US-13", title: "Rich text chapter editor", capability: "drafting.rich-text" },
  { id: "US-14", title: "Focus and reading modes", capability: "drafting.modes" },
  { id: "US-15", title: "Writing goals and analytics", capability: "goals.analytics" },
  { id: "US-16", title: "Global search/replace", capability: "manuscript.search-replace" },
  { id: "US-17", title: "Comments/annotations/tags", capability: "annotation.tags" },
  { id: "US-18", title: "Undo/redo and autosave recovery", capability: "editor.undo-redo.snapshots" },
  { id: "US-19", title: "Compare versions and restore", capability: "snapshot.restore" },
  { id: "US-20", title: "Convert scene cards to draft", capability: "scene.card-to-draft" },
  { id: "US-21", title: "Configure provider-agnostic AI models", capability: "ai.provider.settings" },
  { id: "US-22", title: "Tune AI behavior by scope", capability: "settings.precedence.scopes" },
  { id: "US-23", title: "Run AI actions", capability: "ai.action.set" },
  { id: "US-24", title: "Style transform by ghostwriter profile", capability: "ai.style.transform" },
  { id: "US-25", title: "Consistency checks", capability: "ai.consistency.check" },
  { id: "US-26", title: "Apply AI edits via preview", capability: "ai.preview.apply" },
  { id: "US-27", title: "Inspect AI action logs", capability: "ai.logs" },
  { id: "US-28", title: "Execute revision passes", capability: "revision.pass" },
  { id: "US-29", title: "Track revision issues", capability: "revision.issues" },
  { id: "US-30", title: "Quality scoring with rubric", capability: "revision.rubric" },
  { id: "US-31", title: "Grammar/style suggestions", capability: "revision.grammar" },
  { id: "US-32", title: "Custom checklists", capability: "checklist.custom" },
  { id: "US-33", title: "Lock sections from AI rewrite", capability: "chapter.ai.lock" },
  { id: "US-34", title: "Export Markdown and JSON", capability: "export.markdown.json" },
  { id: "US-35", title: "Import Markdown/TXT/JSON", capability: "import.markdown.txt.json" },
  { id: "US-36", title: "Generate publishing artifacts", capability: "publish.artifacts" },
  { id: "US-37", title: "Generate marketing content", capability: "marketing.artifacts" },
  { id: "US-38", title: "Generate cover brief prompts", capability: "marketing.cover-brief" },
  { id: "US-39", title: "Launch checklists", capability: "marketing.launch.checklist" },
  { id: "US-40", title: "Configuration precedence", capability: "settings.precedence" },
  { id: "US-41", title: "Reset selected settings domains", capability: "settings.reset.scope" },
  { id: "US-42", title: "Inspect offline/queue state", capability: "offline.queue.status" },
  { id: "US-43", title: "Install as PWA", capability: "pwa.install" },
  { id: "US-44", title: "Recover from interrupted AI ops", capability: "ai.error.recovery" },
  { id: "US-45", title: "Keyboard shortcuts", capability: "shortcuts.core" },
  { id: "US-46", title: "Accessible UI", capability: "a11y.keyboard.aria" },
  { id: "US-47", title: "Responsive UI", capability: "ui.responsive" },
  { id: "US-48", title: "No fake placeholders", capability: "real.flows.only" },
  { id: "US-49", title: "Switch UI language between French and English", capability: "i18n.locale.switch" },
  { id: "US-50", title: "Use dark and light mode with consistent styling", capability: "theme.dual-mode" },
  { id: "US-51", title: "Visualize writing goal progression", capability: "goals.dashboard.progression" },
  { id: "US-52", title: "Manage multiple projects and switch cleanly", capability: "project.library.multi-project" },
  { id: "US-53", title: "Track evolution of actors, chapters, locations, lore and scenes", capability: "canon.progression.story-level" },
  { id: "US-54", title: "Check story bible and scene consistency with AI guidance", capability: "canon.consistency.ai-assisted" },
  { id: "US-55", title: "Manage character relationships and their evolution", capability: "relationships.character.character" },
  { id: "US-56", title: "Manage character-location relationships and their evolution", capability: "relationships.character.location" },
  { id: "US-57", title: "Manage character-lore relationships and their evolution", capability: "relationships.character.lore" },
  { id: "US-58", title: "Manage character-timeline relationships and their evolution", capability: "relationships.character.timeline" },
  { id: "US-59", title: "Manage location-lore relationships and their evolution", capability: "relationships.location.lore" },
  { id: "US-60", title: "Manage location-timeline relationships and their evolution", capability: "relationships.location.timeline" },
  { id: "US-61", title: "Manage lore-timeline relationships and their evolution", capability: "relationships.lore.timeline" },
  { id: "US-62", title: "Manage combined canon relationships across tracked entities", capability: "relationships.cross-entity.story" },
  { id: "US-63", title: "Track canon relationships by chapter and scene", capability: "relationships.cross-entity.scene" },
  { id: "US-64", title: "Receive AI suggestions on chapter and scene canon drift", capability: "relationships.cross-entity.ai-fix" },
  { id: "US-65", title: "Track inventory, knowledge, and POV relationships", capability: "pov.inventory.knowledge" },
  { id: "US-66", title: "Manage narration status of locations over story progression", capability: "location.status.progression" },
];

export function getUserStory(id: string): UserStory | undefined {
  return USER_STORIES.find((story) => story.id === id);
}
